# Make file for parser

compile:
	gcc create_parse_table.c create_parse_tree.c find_first_recursive.c read_ff.c \
	read_grammer.c ../../utils/stack.c ../../utils/tree.c ../../utils/token.c \
	-o parser.exe
